# These are supported funding model platforms

# github: drsensor # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: DrSensor
paypal: https://www.paypal.me/cimenx
gitstore: https://enjoy.gitstore.app/repositories/DrSensor/scdlang
# open_collective: # Replace with a single Open Collective username
# ko_fi: # Replace with a single Ko-fi username
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
# custom: # Replace with a single custom sponsorship URL