# These are supported funding model platforms

# github: drsensor # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
ko_fi: drsensor
patreon: DrSensor
# open_collective: # Replace with a single Open Collective username
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
# custom: # Replace with a single custom sponsorship URL
