[package]
name = "scdlang_xstate"
version = "0.2.1"
description = "Scdlang parser for targeting JavaScript library XState"
license = "UPL-1.0"
repository = "https://github.com/drsensor/scdlang"
authors = ["Fahmi Akbar Wildana <f.a.wildana@gmail.com>"]
keywords = ["dsl", "statemachine", "language"]
categories = ["parser-implementations"]
edition = "2018"

[dependencies]
scdlang = { path = "../../core", version = "0.2.1" }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
serde_with = { version = "1", features = ["json"] }
voca_rs = "1" # helper to convert Scdlang naming convention into DavidKPiano naming convention
# for custom options
strum = { git = "https://github.com/Peternator7/strum.git" }
strum_macros = { git = "https://github.com/Peternator7/strum.git" }

[dev-dependencies]
assert-json-diff = "1"