[package]
name = "scdlang_xstate"
version = "0.1.0"
description = "Scdlang parser for targeting JavaScript library XState"
license = "UPL-1.0"
repository = "https://github.com/drsensor/scdlang"
authors = ["Fahmi Akbar Wildana <f.a.wildana@gmail.com>"]
keywords = ["dsl", "statemachine", "language"]
categories = ["parser-implementations"]
edition = "2018"

[dependencies]
scdlang = { path = "../../core", version = "0.1.0" }
serde_json = "*"
serde = { version = "*", features = ["derive"] }
pest-ast = "*"
from-pest = "*"
pest = "*"
voca_rs = "*"

[dev-dependencies]
assert-json-diff = "*"