[package]
name = "scdlang"
version = "0.2.1"
description = "Core parser of Statecharts Description Languange"
license = "UPL-1.0"
repository = "https://github.com/drsensor/scdlang"
authors = ["Fahmi Akbar Wildana <f.a.wildana@gmail.com>"]
# readme = "../../README.md" # WARNING: bugs! it's not resolved to relative path
keywords = ["dsl", "statemachine", "language"]
categories = ["parsing"]
edition = "2018"

[dependencies]
# parser + context-free-grammar
pest = "2"
pest_derive = "2"
# helper
lazy_static = "1" # to define the global caches
either = "1" # a workaround for iterator.filter that return Result<Vec, _>
static_assertions = "0.3" # design-by-contract at compile time

[badges]
maintenance = { status = "actively-developed" }