[package]
name = "scdlang-core"
version = "0.1.1"
authors = ["Fahmi Akbar Wildana <f.a.wildana@gmail.com>"]
edition = "2018"

[dependencies]
pest = "*"
pest_derive = "*"
lazy_static = "*"
either = "*"