[package]
name = "scdlang_smcat"
version = "0.1.1"
authors = ["Fahmi Akbar Wildana <f.a.wildana@gmail.com>"]
edition = "2018"

[dependencies]
scdlang = { path = "../../core", version = "0.1.1" }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
serde_with = { version = "1", features = ["json"] }

[dev-dependencies]
assert-json-diff = "1"