[package]
name = "s-crap"
version = "0.2.1"
description = "A CLI for working with Scdlang"
license = "UPL-1.0"
repository = "https://github.com/drsensor/scdlang"
authors = ["Fahmi Akbar Wildana <f.a.wildana@gmail.com>"]
keywords = ["statemachine", "language", "cli", "scdlang"]
categories = ["command-line-utilities"]
edition = "2018"

[[bin]]
name = "scrap"
path = "src/main.rs"
test = false 	# TODO: remove integration test and replace it with evlish or bats
							# CLI tests should be readable and close to shell scripting environment
doc = false
doctest = false

[lib]
doctest = false
doc = false

[dependencies]
scdlang = { path = "../core", version = "0.2.1" }
scdlang_xstate = { path = "../transpiler/xstate", version = "0.2.1" }
scdlang_smcat = { path = "../transpiler/smcat", version = "0.2.1" }
atty = "0.2"
rustyline = "5"
prettyprint = "0.*"
colored = "1"
which = "2"
regex = "1"
voca_rs = "1"

[dependencies.clap]
version = "2"
features = ["wrap_help", "color"]

[dev-dependencies]
predicates = "1"
assert_fs = "0.*"
assert_cmd = "0.*"
rexpect = "0.3"