[package]
name = "scrap"
version = "0.1.0"
description = "A devtools for scdlang"
authors = ["Fahmi Akbar Wildana <f.a.wildana@gmail.com>"]
edition = "2018"

[dependencies]
atty = "*"

[dependencies.clap]
version = "*"
features = ["wrap_help"]

[dev-dependencies]
assert_cmd = "*"
rexpect = "*"